### ISSUE TITLE
adcioning a world

### ISSUE THREAD

**Issue by BoyJPN** [AIPTU/WorldTime#1]
when I add a world the crash server, and I can not open could fix this error?

**Comment by AIPTU** [comment]
Is there a crash dump and can you show me your configuration?

**Comment by BoyJPN** [comment]
Yes

**Comment by BoyJPN** [comment]
wait for me to get home and i'll show you

**Comment by BoyKage** [comment]
---
# Do not change this (Only for internal use)!
config-version: 1.0

# Message used when setting world time.
# Available tags:
# - {WORLD}: Show world folder name.
# - {TIME}: Show world time.
message: "Definir o tempo do {WORLD} mundo para {TIME}"

worlds:
  # World folder name.
  world: Lobby
    # World time to set.
  time: day
    # Stop time
  stop: true
  # World folder name with spaces.
  "example world":
    time: night
    stop: false
...

**Comment by BoyJPN** [comment]
---
 Do not change this (Only for internal use)!
config-version: 1.0

 Message used when setting world time.
 Available tags:
 - {WORLD}: Show world folder name.
 - {TIME}: Show world time.
message: "Definir o tempo do {WORLD} mundo para {TIME}"

worlds:
    World folder name.
  world: Lobby
      World time to set.
  time: day
      Stop time
  stop: true
    World folder name with spaces.
  "example world":
    time: night
    stop: false
...

**Comment by BoyJPN** [comment]
<html>
<body>


2022-08-09 [19:30:12.833] [Server thread/CRITICAL]: TypeError: "Cannot access offset of type string on string" (EXCEPTION) in "plugins/WorldTime.phar/src/WorldTime" at line 85
--
73 | --- Stack trace ---
74 | #0 plugins/WorldTime.phar/src/WorldTime(47): aiptu\worldtime\WorldTime->checkWorld()
75 | #1 pmsrc/src/plugin/PluginBase(117): aiptu\worldtime\WorldTime->onEnable()
76 | #2 pmsrc/src/plugin/PluginManager(448): pocketmine\plugin\PluginBase->onEnableStateChange(true)
77 | #3 pmsrc/src/Server(1419): pocketmine\plugin\PluginManager->enablePlugin(object aiptu\worldtime\WorldTime#26311)
78 | #4 pmsrc/src/Server(1024): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#25753)
79 | #5 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[8] /server/, string[16] /server/plugins/)
80 | #6 pmsrc/src/PocketMine(327): pocketmine\server()
81 | #7 pmsrc(11): require(string[45] phar:///server/server.phar/src/PocketMine.php)
82 | --- End of exception information ---
83 | 2022-08-09 [19:30:12.834] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
84 | 2022-08-09 [19:30:12.842] [Server thread/EMERGENCY]: Please upload the "/server/crashdumps/Tue_Aug_9-19.30.12--03_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
85 | 2022-08-09 [19:30:12.986] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/7329816 or use the ID #7329816.
86 | 2022-08-09 [19:30:12.986] [Server thread/EMERGENCY]: Forcing server shutdown


</body>
</html>2022-08-09 [19:30:12.833] [Server thread/CRITICAL]: TypeError: "Cannot access offset of type string on string" (EXCEPTION) in "plugins/WorldTime.phar/src/WorldTime" at line 85
--- Stack trace ---
  #0 plugins/WorldTime.phar/src/WorldTime(47): aiptu\worldtime\WorldTime->checkWorld()
  #1 pmsrc/src/plugin/PluginBase(117): aiptu\worldtime\WorldTime->onEnable()
  #2 pmsrc/src/plugin/PluginManager(448): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #3 pmsrc/src/Server(1419): pocketmine\plugin\PluginManager->enablePlugin(object aiptu\worldtime\WorldTime#26311)
  #4 pmsrc/src/Server(1024): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#25753)
  #5 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[8] /server/, string[16] /server/plugins/)
  #6 pmsrc/src/PocketMine(327): pocketmine\server()
  #7 pmsrc(11): require(string[45] phar:///server/server.phar/src/PocketMine.php)
--- End of exception information ---
2022-08-09 [19:30:12.834] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
2022-08-09 [19:30:12.842] [Server thread/EMERGENCY]: Please upload the "/server/crashdumps/Tue_Aug_9-19.30.12--03_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
2022-08-09 [19:30:12.986] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/[73](https://aternos.org/log/#L73)29[81](https://aternos.org/log/#L81)6 or use the ID #7329816.
2022-08-09 [19:30:12.986] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by AIPTU** [comment]
This looks like your configuration is wrong

**Comment by AIPTU** [comment]
You can copy this and try it out
```yaml
---
# Do not change this (Only for internal use)!
config-version: 1.0

# Message used when setting world time.
# Available tags:
# - {WORLD}: Show world folder name.
# - {TIME}: Show world time.
message: "Set the time of the {WORLD} world to {TIME}"

worlds:
  # World folder name.
  world:
    # World time to set.
    time: day
    # Stop time
    stop: true
  # World folder name with spaces.
  "example world":
    time: night
    stop: false
...

```

**Comment by AIPTU** [comment]
If you want to add another world, you can follow the format as for example

**Comment by BoyJPN** [comment]
but how do i do it? where can i put the name of the world?

**Comment by BoyJPN** [comment]
Hello?

**Comment by AIPTU** [comment]
You just need to follow the sample format

**Comment by AIPTU** [comment]
Like this
```yaml
---
worlds:
  # World folder name.
  world:
    # World time to set.
    time: day
    # Stop time
    stop: true
  # World folder name with spaces.
  "example world":
    time: night
    stop: false
  "SkyBlock":
    time: day
    stop: false
  "anjay":
    time: day
    stop: true
...
```
